src/Movidon/BackendBundle/Entity/AdminUser.php
<?php
namespace Movidon\BackendBundle\Entity;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Movidon\BackendBundle\Entity\AdminUserRepository")
 * @DoctrineAssert\UniqueEntity("username")
 * @UniqueEntity("username")
 */
class AdminUser implements AdvancedUserInterface, \Serializable, EquatableInterface
{
    const AUTH_SALT = "R4y0d3Lu24b1sMa7";

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=250, unique=true)
     */
    protected $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 6)
     * */
    protected $password;

    /**
     * @ORM\Column(name="salt", type="string", length=255)
     */
    protected $salt;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="registeredDate", type="datetime", nullable=true)
     * @Assert\Date()
     */
    protected $registeredDate;

    /**
     * @ORM\ManyToMany(targetEntity="Movidon\BlogBundle\Entity\Post", mappedBy="authors")
     */
    protected $posts;

    /**
     * @ORM\ManyToOne(targetEntity="Movidon\ImageBundle\Entity\ImageAvatar")
     */
    protected $avatar;

    /**
     * @ORM\OneToMany(targetEntity="Movidon\ImageBundle\Entity\ImageProfile", mappedBy="user", cascade={"persist", "remove", "merge"})
     */
    protected $imagesProfile;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $lastName;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $summary;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $aboutMe;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     * @Assert\Email();
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $twitter;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $website;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $degree;

    /**
     * @Gedmo\Slug(fields={"name", "lastName"}, updatable=true)
     * @ORM\Column(name="slug", type="string", length=255, nullable=true)
     */
    protected $slug;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $visits;

    /**
     * @ORM\ManyToMany(targetEntity="Movidon\BackendBundle\Entity\Role", inversedBy="users")
     * @ORM\JoinTable(name="users_roles",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="role_id", referencedColumnName="id")}
     *      )
     */
    protected $roles;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default" = 0})
     */
    protected $banned = false;

    /**
     * @ORM\ManyToMany(targetEntity="Movidon\MessageBundle\Entity\Thread", mappedBy="participants")
     */
    protected $threads;

    /**
     * @ORM\OneToMany(targetEntity="Movidon\BlogBundle\Entity\Feedback", mappedBy="author", cascade={"persist", "remove", "merge"})
     */
    protected $feedbacks;

    public function __construct()
    {
        $this->imagesProfile = new \Doctrine\Common\Collections\ArrayCollection();
        $this->roles = new \Doctrine\Common\Collections\ArrayCollection();
        $this->threads = new \Doctrine\Common\Collections\ArrayCollection();
        $this->feedbacks = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function serialize()
    {
        return serialize(array($this->id, $this->password, $this->username));
    }

    public function unserialize($serialized)
    {
        list($this->id, $this->password, $this->username) = unserialize(
            $serialized);
    }

    public function __toString()
    {

        return ucfirst($this->getUsername());
    }

    public function isEqualTo(
        \Symfony\Component\Security\Core\User\UserInterface $user)
    {
        return $this->getUsername() == $user->getUsername();
    }

    public function eraseCredentials()
    {
    }

    public function getRoles()
    {
        if ($this->banned) {
            return array('ROLE_BANNED');
        }

        $roles = array();
        foreach ($this->roles as $role) {
            $roles[] = $role->getNameWithPrefix();
        }

        // Default role
        if (count($roles) === 0) {
            $roles[] = 'ROLE_SUPER_ADMIN';
        }

        return $roles;
    }

    public function getCustomRoles()
    {
        return $this->roles;
    }

    public function getRolesAsString()
    {
        $result = '';
        foreach ($this->roles as $role) {
            $result .= $role->getNameWithPrefix();
            if ($role !== $this->roles->last()) {
                $result .= ', ';
            }
        }

        // Default role
        if (strlen($result) === 0) {
            $result = 'ROLE_SUPER_ADMIN';
        }
        return $result;
    }

    public function setRoles($roles)
    {
        $this->roles = $roles;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getSalt()
    {
        return $this->salt;
    }

    public function setSalt($salt)
    {
        $this->salt = $salt;
    }

    public function getRegisteredDate()
    {
        return $this->registeredDate;
    }

    public function getUsername()
    {
        return ucfirst($this->username);
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    /**
     * @return mixed
     */
    public function getPosts()
    {
        return $this->posts;
    }

    /**
     * @param mixed $posts
     */
    public function setPosts($posts)
    {
        $this->posts = $posts;
    }

    /**
     * @return mixed
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * @param mixed $avatar
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return ucfirst($this->name);
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return ucfirst($this->lastName);
    }

    /**
     * @param mixed $lastName
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
    }

    /**
     * @return mixed
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * @param mixed $summary
     */
    public function setSummary($summary)
    {
        $this->summary = $summary;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getTwitter()
    {
        return $this->twitter;
    }

    /**
     * @param mixed $twitter
     */
    public function setTwitter($twitter)
    {
        $this->twitter = $twitter;
    }

    /**
     * @return mixed
     */
    public function getWebsite()
    {
        return $this->website;
    }

    /**
     * @param mixed $website
     */
    public function setWebsite($website)
    {
        $this->website = $website;
    }

    /**
     * @return mixed
     */
    public function getImagesProfile()
    {
        return $this->imagesProfile;
    }

    /**
     * @param mixed $imageProfile
     */
    public function setImagesProfile($imagesProfile)
    {
        $this->imagesProfile = $imagesProfile;
    }

    public function getImageProfile()
    {
        foreach ($this->imagesProfile as $image) {
            if ($image->getMain()) {
                return $image;
            }
        }

        return null;
    }

    /**
     * @return mixed
     */
    public function getVisits()
    {
        return $this->visits;
    }

    /**
     * @param mixed $visits
     */
    public function setVisits($visits)
    {
        $this->visits = $visits;
    }

    /**
     * @return mixed
     */
    public function getDegree()
    {
        return $this->degree;
    }

    /**
     * @param mixed $degree
     */
    public function setDegree($degree)
    {
        $this->degree = $degree;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    /**
     * @return mixed
     */
    public function getAboutMe()
    {
        return $this->aboutMe;
    }

    /**
     * @param mixed $aboutMe
     */
    public function setAboutMe($aboutMe)
    {
        $this->aboutMe = $aboutMe;
    }

    /**
     * @return mixed
     */
    public function getBanned()
    {
        return $this->banned;
    }

    /**
     * @param mixed $banned
     */
    public function setBanned($banned)
    {
        $this->banned = $banned;
    }

    /**

src/Movidon/BackendBundle/Controller/UserController.php
<?php

namespace Movidon\BackendBundle\Controller;

use Movidon\BackendBundle\Entity\AdminUser;
use Movidon\BackendBundle\Form\Type\AdminUserType;
use Movidon\BackendBundle\Utils\UpdateEntityHelper;
use Movidon\ImageBundle\Form\Type\ImageType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Movidon\FrontendBundle\Controller\CustomController;
use Symfony\Component\HttpFoundation\Request;

class UserController extends CustomController
{
    public function listAction()
    {
        $em = $this->getEntityManager();
        $paginator = $this->get('ideup.simple_paginator');
        $paginator->setItemsPerPage(CustomController::ITEMS_PER_PAGE, 'users');
        $users = $paginator->paginate($em->getRepository('BackendBundle:AdminUser')->findAllDQL(), 'users')->getResult();

        return $this->render('BackendBundle:Admin:User/list.html.twig', array('users' => $users));
    }

    public function createAction(Request $request)
    {
        $user = new AdminUser();
        $form = $this->createForm(new AdminUserType(), $user);
        $handler = $this->get('admin.admin_user_form_handler');

        if ($handler->handle($form, $request)) {
            $this->setTranslatedFlashMessage('The new user has been created successfully');

            return $this->redirect($this->generateUrl('super_admin_user_index'));
        } else {
            if ($request->isMethod('POST'))
                $this->setTranslatedFlashMessage('There is an error in your request', 'error');
        }

        return $this->render('BackendBundle:Admin:User/create.html.twig', array('form' => $form->createView()));
    }

    /**
     * @ParamConverter("user", class="BackendBundle:AdminUser")
     */
    public function editAction(AdminUser $user, Request $request)
    {
        $form = $this->createForm(new AdminUserType(), $user);
        $handler = $this->get('admin.admin_user_form_handler');

        if ($handler->handle($form, $request)) {
            $this->setTranslatedFlashMessage('The user has been edited successfully');

            return $this->redirect($this->generateUrl('super_admin_user_index'));
        } else {
            if ($request->isMethod('POST'))
                $this->setTranslatedFlashMessage('There is an error in your request', 'error');
        }

        return $this->render('BackendBundle:Admin:User/create.html.twig', array('edition' => true, 'user' => $user, 'form' => $form->createView()));
    }

    /**
     * @ParamConverter("user", class="BackendBundle:AdminUser")
     */
    public function deleteAction(AdminUser $user)
    {
        $em = $this->getEntityManager();
        $em->remove($user);
        $em->flush();
        $this->setTranslatedFlashMessage('The user has been removed successfully');

        return $this->redirect($this->generateUrl('super_admin_user_index'));
    }

    /**
     * @ParamConverter("user", class="BackendBundle:AdminUser")
     */
    public function toggleBanAction(AdminUser $user)
    {
        if ($user === $this->getCurrentUser()) {
            $this->setTranslatedFlashMessage('You can not ban yourself!', 'error');
        } else {
            $em = $this->getEntityManager();
            $user->setBanned(!$user->getBanned());
            $em->persist($user);
            $em->flush();
            if ($user->getBanned()) {
                $this->setTranslatedFlashMessage('The user has been banned successfully');
            } else {
                $this->setTranslatedFlashMessage('The user is no longer banned');
            }
        }

        return $this->redirect($this->generateUrl('super_admin_user_index'));
    }

    /**
     * @ParamConverter("user", class="BackendBundle:AdminUser")
     */
    public function profileAction(AdminUser $user, Request $request)
    {
        $form = $this->createForm(new ImageType());
        $imagesHandler = $this->get('image.form_handler');

        if ($request->isMethod('post') &&
            !$imagesHandler->handle($form, $request, $user)) {
            $this->setTranslatedFlashMessage('Profile image could not be updated', 'error');
        }

        return $this->render('BackendBundle:Admin:Profile/profile.html.twig', array('user' => $user, 'form' => $form->createView(), 'superadmin' => true));
    }

    /**
     * @ParamConverter("user", class="BackendBundle:AdminUser")
     */
    public function updateProfileAction(AdminUser $user, Request $request)
    {
        $json_response = json_encode(array('ok' => false));
        if ($request->isXmlHttpRequest()) {
            $em = $this->getEntityManager();

            $data = $request->request->all();
            $data = $data['admin_user_profile'];

            $updatedValues = UpdateEntityHelper::updateEntity($data, $user, 'admin_user_profile_');

            $em->persist($user);
            $em->flush();
            $json_response = json_encode(array('ok' => true, 'updatedValues' => $updatedValues));
        }

        return $this->getHttpJsonResponse($json_response);
    }
}

src/Movidon/BackendBundle/Resources/views/Admin/User/create.html.twig
{% extends 'BackendBundle:Layouts:2columns.html.twig' %}

{% block breadcrumb %}
    {% if edition is defined %}
        {% set crumbs = {'Users': path('super_admin_user_index'), 'Edit user': '' } %}
    {% else %}
        {% set crumbs = {'Users': path('super_admin_user_index'), 'Create user': '' } %}
    {% endif %}

    {{ setCrumbs(crumbs) }}
    {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/backend/css/select2.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('bundles/backend/css/custom.select2.css') }}" />
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="card-item card-green">
                <form autocomplete="off" method="post" action="{% if edition is defined %}{{ path('super_admin_user_edit',{'id':user.id}) }} {% else %} {{ path('super_admin_user_create') }}{% endif %}">
                    <div class="card-title">
                        <h2>
                            {% if edition is defined %}
                                {{ 'User edition' | trans }}
                            {% else %}
                                {{ 'User creation' | trans }}
                            {% endif %}
                        </h2>

                        <h3>
                            {% if edition is defined %}
                                {{ 'Here you can edit the user' | trans }}
                            {% else %}
                                {{ 'Here you can create new users' | trans }}
                            {% endif %}
                        </h3>

                        <button type="submit" class="float-action-button fab-red borderless">
                            <i class="fa fa-check"></i>
                        </button>
                    </div>
                    <div class="card-description card-padding">
                        <div class="row">
                            <div class="col-md-8">
                                {% include 'BackendBundle:Admin:User/user-form.html.twig' %}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/backend/js/select2.min.js') }}"></script>
    <script>
        window.addEventListener('load', function(evt) {
            $(".select2").select2();
            {% if edition is defined %}
                var pwd = document.querySelector('#admin_user_password_first');
                pwd.required = '';
                var pwd2 = document.querySelector('#admin_user_password_second');
                pwd2.required = '';
                //console.info(pwd.setAttribute('value', ''));
            {% endif %}
        });
    </script>
{% endblock %}

src/Movidon/BackendBundle/Resources/views/Admin/User/list.html.twig
{% extends 'BackendBundle:Layouts:2columns.html.twig' %}

{% block breadcrumb %}
    {{ setCrumbs({'Users': ''}) }}
    {{ parent() }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card-item card-green">
                    <div class="card-title">
                        <h2>
                            {{ 'Users list' | trans }}
                        </h2>

                        <h3>
                            {{ 'In this panel you can edit or delete every registered user' | trans }}
                        </h3>

                        <a title="{{ 'Create new User' | trans }}" class="float-action-button fab-red" href="{{ path('super_admin_user_create') }}">
                            <i class="fa fa-plus"></i>
                        </a>
                    </div>
                <div class="card-description {% if users | length == 0 %}card-padding{% endif %}">
                    {% if users | length > 0 %}
                    <table class="table table-hover table-striped data-table">
                        <thead>
                        <tr>
                            <th>{{ 'ID' | trans }}</th>
                            <th>{{ 'Username' | trans }}</th>
                            <th>{{ 'Roles' | trans }}</th>
                            <th>{{ 'Banned' | trans }}</th>
                            <th>{{ 'Action' | trans }}</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.rolesAsString }}</td>
                            <td>{% if user.banned %}{{ 'Yes' | trans }}{% else %}{{ 'No' | trans }}{% endif %}</td>
                            <td>
                                {% if user.banned %}
                                    <a class="publish btn btn-amber" href="{{ path('super_admin_user_toggle_ban', {'id': user.id}) }}" title="{{ 'Active user' | trans }}"><i class="fa fa-check"></i></a>
                                {% else %}
                                    <a class="publish btn btn-amber" href="{{ path('super_admin_user_toggle_ban', {'id': user.id}) }}" title="{{ 'Ban user' | trans }}"><i class="fa fa-times"></i></a>
                                {% endif %}
                                <a class="edit btn btn-blue" href="{{ path('super_admin_user_edit', {'id': user.id}) }}" title="{{ 'Edit user' | trans }}"><i class="fa fa-pencil"></i></a>
                                <a class="btn btn-purple" href="{{ path('super_admin_user_profile', {'id': user.id}) }}" title="{{ 'View profile' | trans }}"><i class="fa fa-eye"></i></a>
                                <a class="delete btn btn-red" href="{{ path('super_admin_user_delete', {'id': user.id}) }}" title="{{ 'Delete user' | trans }}"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                    {% else %}
                        <p>
                            {{ 'No entries were found' | trans }}
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Movidon/BackendBundle/Resources/views/Admin/User/user-form.html.twig
{% if edition is defined %}
    {% set required = 'false' %}
    {% set placeholder = 'New password' | trans %}
{% else %}
    {% set required = 'true' %}
    {% set placeholder = 'Password' | trans %}
{% endif %}
<div class="form-group">
    <div class="input-group">
        <span class="input-group-addon">
            <i class="fa fa-user"></i>
        </span>
        <div class="line">
            {{ form_widget(form.username, {'attr': {'class': 'form-control', 'placeholder': 'Username'}}) }}
        </div>
    </div>
</div>

<div class="form-group">
    <div class="input-group">
        <span class="input-group-addon">
            <i class="fa fa-lock"></i>
        </span>
        <div class="line">
            {{ form_widget(form.password.first, {'attr': {'class': 'form-control', 'placeholder': placeholder, 'autocomplete': 'off'}}) }}
        </div>
    </div>
</div>

<div class="form-group">
    <div class="input-group">
        <span class="input-group-addon">
            <i class="fa fa-lock"></i>
        </span>
        <div class="line">
            {{ form_widget(form.password.second, {'attr': {'class': 'form-control', 'placeholder': 'Repeat password'}}) }}
        </div>
    </div>
</div>

<div class="form-group">
    <label>{{ 'User roles' | trans }}</label>
    <div class="line">
        {{ form_widget(form.customRoles, { 'attr': { 'class': 'form-control required select2', 'placeholder': 'User roles' | trans} }) }}
    </div>
    <small class="help-block">
        {{ 'Choose as many roles as you want' | trans }}
    </small>
</div>

{{ form_rest(form) }}